version: "3"

vars:
  BINARY_NAME: devenv
  SOURCE_DIR: cmd/devenv
  BUILD_DIR: bin
  MANIFEST_BUILD_DIR: build

tasks:
  build:
    desc: Build the binary
    cmds:
      - mkdir -p {{.BUILD_DIR}}
      - go build -o {{.BUILD_DIR}}/{{.BINARY_NAME}} ./{{.SOURCE_DIR}}

  clean:
    desc: Clean build artifacts
    cmds:
      - go clean
      - rm -rf {{.BUILD_DIR}}
      - rm -rf {{.MANIFEST_BUILD_DIR}}

  test:
    desc: Run tests
    cmds:
      - go test ./... {{.CLI_ARGS}}

  doc:
    desc: Launch pkgsite documentation server
    cmds:
      - pkgsite -open
